config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tickets, only: :show

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  
  get '/tickets/pages/:id', to: 'tickets#paginate', as: 'paginate'
  root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(status: 404)
  end

  def internal_server_error
    render(status: 500)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  include HTTParty
  
  def paginate

    if (params[:id].to_i < 1) || (all_digits(params[:id]) == false)
      raise ActionController::RoutingError.new('not_found')
    else
      @page_number = params[:id].to_i
    end

    @response = HTTParty.get("https://donatoivan.zendesk.com/api/v2/tickets.json?page=#{@page_number}&per_page=25",
                      basic_auth: credentials)

    if (check_error(@response) != true) && (@response['tickets'].empty? == true)
      raise ActionController::RoutingError.new('not_found')
    elsif check_error(@response) != true 
      @tickets = @response.parsed_response['tickets']
    elsif check_error(@response) 
      render :error
    end
    
  end

  def show
    @response = HTTParty.get("https://donatoivan.zendesk.com/api/v2/tickets/#{params[:id]}.json", 
                      basic_auth: credentials)

    check_error(@response) ? (render :error) : @ticket = @response.parsed_response['ticket']
    
    if @response.parsed_response['error'] == 'RecordNotFound'
      raise ActionController::RoutingError.new('not_found')
    end
  end

  private
  def credentials
    @auth = {username: Rails.application.credentials.zendesk_api[:username], 
      password: Rails.application.credentials.zendesk_api[:password]}
  end

  def check_error(response)
    if (response.code == 404 || response.code == 401 || response.code == 503)
      true
    end   
  end

  def all_digits(str)
    str[/[0-9]+/] == str
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<nav class="home-nav">
  <%= link_to "zendesk", root_path, class: "home-nav-icon" %>
</nav>
<div class="container">
  <div class="content">
    <h1 class="welcome-message">Welcome to the Zendesk Ticket Viewer</h1>
    <br>
    <p class="sub-heading">
      A Zendesk Internship Coding Challenge
    </p>
    <%= link_to "View Tickets", paginate_path(1), class: "call-to-action-button" %>
  </div>
  <div class="image">
    <%= image_tag("illustration-truck.png", class: "image-sizing") %>
  </div>
</div>

app/views/layouts/_background.html.erb
<% case @page_number %>
<% when 1 %>
  green
<% when 2 %>
  pink
<% when 3 %>
  orange
<% when 4 %>
  blue
<% when 5 %>
  blood-orange
<% end %>

app/views/layouts/_bottom_nav.html.erb
<div class="the-core-of-earth <%= render partial: "layouts/background" %>"">
  <%= render 'tickets/ticket-list-pagination', obj: @response  %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZendeskInternshipCodingChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_ticket-body.html.erb
<% if obj['id'] >= 1 && obj['id'] <= 25 %>
  green
<% elsif obj['id'] >= 26 && obj['id'] <= 50 %> %>
  pink
<% elsif obj['id'] >= 51 && obj['id'] <= 75 %> %>
  orange
<% elsif obj['id'] >= 76 && obj['id'] <= 100 %> %>
  blue
<% else %>
  blood-orange
<% end %>

app/views/tickets/_ticket-list-pagination.html.erb
<% if obj['previous_page'] == nil %>
    <div class="pagination-links">
      <%= link_to "Next page >", paginate_path(@page_number + 1), class: "page-links"  %>
    </div>
  <% elsif obj['next_page'] == nil %>
    <div class="pagination-links">
      <%= link_to "< Previous Page", paginate_path(@page_number - 1), class: "page-links" %>
    </div>
  <% else %>
    <div class="pagination-links">
      <%= link_to "< Previous Page", paginate_path(@page_number - 1), class: "page-links"%>
      <%= link_to "Next page >" , paginate_path(@page_number + 1), class: "page-links"  %>
    </div>
  <% end %>

app/views/tickets/_ticket-nav.html.erb
<nav class="home-nav">
  <a href="/" class="tickets-nav-icon">
    <%= image_tag("zendesk-medium-textless.png", class: "zendesk-icon-sizing") %>
  </a>
</nav>

app/views/tickets/error.html.erb
<nav class="home-nav">
  <%= link_to "zendesk", root_path, class: "home-nav-icon" %>
</nav>
<div class="container">
  <div class="content">
    <h4 class="error-heading">You might not have the right authentication details or the Api might be down</h4>
    <br>
    <p class="sub-heading">
      Check for any typos, including the Api URL
    </p>
    <%= link_to "Back to Tickets", paginate_path(1), class: "call-to-action-button" %>
  </div>
  <div class="image">
    <%= image_tag("error.svg", class: "image-sizing") %>
  </div>
</div>

app/views/tickets/paginate.html.erb
<div class="tickets-container <%= render partial: "layouts/background" %>">
  <div class="content-wrap">
    <%= render 'tickets/ticket-nav' %>
    <h1 class="all-tickets-header">All Tickets</h1>
    <%= render 'tickets/ticket-list-pagination', obj: @response  %>

    <% @tickets.each do |ticket| %>
      <div class="ticket-box">
        <div class="ticket-id"><i class="fas fa-lightbulb fa-2x"></i><h4>id#<%= ticket['id'] %></h4></div>
        <div class="duo">
          <div class="subject"><strong>Subject: </strong> <%= ticket['subject'].truncate_words(4) %></div>
          <br>
          <div class = "description"><strong>Description: </strong> <%= ticket['description'].truncate_words(5) %></div>
        </div>
        <%= link_to "View Ticket", ticket_path(ticket['id']), class: "show-ticket" %>
      </div>
    <% end %>
  </div>
  <%= render 'layouts/bottom_nav.html.erb' %>
</div>

app/views/tickets/show.html.erb
<div class="ticket-container <%= render 'tickets/ticket-body', obj: @ticket %>">
  <%= render 'tickets/ticket-nav' %>
  <h1 class="all-tickets-header"><i class="fas fa-lightbulb"></i> Ticket id#<%= @ticket['id'] %></h1>

  <div class="single-ticket-box">
    <div class="single-ticket-date"><%= 
          "#{@ticket['created_at'].split("T")[0].split("-")[2]}/
          #{@ticket['created_at'].split("T")[0].split("-")[1]}/
          #{@ticket['created_at'].split("T")[0].split("-")[0]}" %>
    </div>
    <p class="single-ticket-subject"><strong><%= @ticket['subject'] %></strong></p>
    <p class="single-ticket-description"><%= @ticket['description'] %></p>
    <ul class="single-ticket-tags">
      <li class="tag-header">Tags:</li>
      <% @ticket['tags'].each do |tag| %>
        <li class="ticket-tags"><%= tag %></li>
      <% end %>
    </ul>
     <%= link_to "Back to Tickets", :back, class: "back-to-tickets" %>
  </div>
</div>